// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SkiApiServer.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20190219103709_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Entities.Models.PartialRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("Duration");

                    b.Property<long>("Length");

                    b.Property<Guid?>("RoundId");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("PartialRounds");
                });

            modelBuilder.Entity("Entities.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Entities.Models.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RoundId");

                    b.Property<DateTime>("ActionTime");

                    b.Property<Guid?>("LocationId");

                    b.Property<string>("Notes");

                    b.Property<Guid?>("PersonId");

                    b.Property<int>("SkiStyle");

                    b.Property<double>("Temperature");

                    b.Property<int>("TotalKilometers");

                    b.Property<int>("TotalTimeInMinutes");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PersonId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Entities.Models.PartialRound", b =>
                {
                    b.HasOne("Entities.Models.Round", "Round")
                        .WithMany("PartialRounds")
                        .HasForeignKey("RoundId");
                });

            modelBuilder.Entity("Entities.Models.Round", b =>
                {
                    b.HasOne("Entities.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("Entities.Models.Person", "Person")
                        .WithMany("Rounds")
                        .HasForeignKey("PersonId");
                });
#pragma warning restore 612, 618
        }
    }
}
